### ISSUE TITLE
Error 404 not Found when Team was not in past seasons

### ISSUE THREAD

**Issue by luketd** [esilverm/shl-index-ui#153]
While you are on the Teams tab in a season where an Expansion team played. When you are moving from S58 to S55 or below for Seattle Argonauts and Atlanta Inferno, there is a 404 error.

When you are on the teams tab in a season when the expansion team did not exist, it still shows the team area like the picture below
![Capture](https://user-images.githubusercontent.com/19975661/114241237-daadea00-9956-11eb-9d1b-d7e3195bd0cd.PNG)

**Comment by esilverm** [comment]
This is likely because this page is generated by SSG we can instead use SSR to fix it
