### ISSUE TITLE
Standings sorted by P% not points

### ISSUE THREAD

**Issue by esilverm** [esilverm/shl-index-ui#155]
Submitter: Segi
## Describe the bug
When looking at the conference standings, the bottom of the two isn't initially sorted by points. Instead it looks like it's sorted by P%. 

## To Reproduce
- IIHF Index
- Go to Standings
- Click on Conference
- Scroll down to the bottom one
- See error (after Round Robin Day 2 - I sent Teddy a screenshot of it, it won't be visible anymore after the third sim, since Points and P% should be the same then.)

## Desktop
It's showing up on mobile Chrome and desktop Firefox

**Comment by luketd** [comment]
![Capture](https://user-images.githubusercontent.com/19975661/114277802-c3283d00-99fa-11eb-84b0-7e8d5fcf93b8.PNG)

Picture for reference. Japan Should be over Czechia

**Comment by esilverm** [comment]
Silly me, I was sorting by Pct first. Now it sorts by Points desc, and then in the case of a tie by WINS  desc and SOW asc

This is fixed and will be included in the next deploy
