### ISSUE TITLE
PPTOI Rounding Error?

### ISSUE THREAD

**Issue by luketd** [esilverm/shl-index-ui#163]
![uUKezbde](https://user-images.githubusercontent.com/19975661/114935862-aed4ad80-9e09-11eb-8aaa-feca1765adc5.png)
As shown, Manhattan in the preseason has atleast :15 seconds on the power play. Looking at their preseason stats

![Capture](https://user-images.githubusercontent.com/19975661/114935936-c6ac3180-9e09-11eb-81a6-4de7c445e100.PNG)
It shows no PPTOI, so I assume it is a rounding error

**Comment by esilverm** [comment]
I think it has to do with the fact that i'm calculating average. Im gonna look into it.

**Comment by esilverm** [comment]
This will be fixed when I deploy
