### ISSUE TITLE
IIHF and WJC S58 Playoffs Error

### ISSUE THREAD

**Issue by luketd** [esilverm/shl-index-ui#167]
When trying to view the IIHF and WJC playoff section of the index, for any season there is an unexpected error when switching for regular season -> playoffs

https://index.simulationhockey.com/iihf/standings?season=58
https://index.simulationhockey.com/wjc/standings?season=58

**Comment by esilverm** [comment]
Playoffs were just broken in general. Seems to be because there were unnecessary useEffects to switch certain values.
