### ISSUE TITLE
Schedule page appears out of order

### ISSUE THREAD

**Issue by DrunkenTeddy** [esilverm/shl-index-ui#181]
![image0-3](https://user-images.githubusercontent.com/10325684/115964395-30e36700-a4d9-11eb-951b-7879e19b13e4.png)

**Comment by esilverm** [comment]
Makes sense. Gotta fix up the sorting function a bit lol

**Comment by esilverm** [comment]
This seems to be working on my end. What device and browser are you getting this error from

**Comment by esilverm** [comment]
this appears to happen on my own mobile device on Brave which runs chromium, but not on desktop Brave. Ill see what could be causing it

**Comment by esilverm** [comment]
This has been fixed
