### ISSUE TITLE
Correct Stream Page

### ISSUE THREAD

**Issue by Nilint1** [esilverm/shl-index-ui#188]
Via the google api docs, we can only do a search for the youtube video IDs 100 times a day.  Some testing shows that every time a user hits the stream page, up to 2 api calls are made.  

This causes our quota to be exhausted very quickly.

I am proposing the following changes to correct this:

- [x] Create a chron job to query the google api 98 times a day (every hour for 4 leagues over 24 hours [1 x 4 x 24])
- [x] Create a database table that contains the current video ids (one for each league)
- [x] Create an API endpoint containing the video ids for each league
- [x] Update the stream page to hit our api to get the video id

I believe this solution would allow us to make changes to the chron job, if our allotment ever gets increased.

**Comment by DrunkenTeddy** [comment]
We can work together on this. Also I'd suggest we poll more often during the day and less often over night, that way we are more likely to catch the stream when it's live.

**Comment by Nilint1** [comment]
I think that would be fine.  But, probably an enhancement after we get it working

**Comment by Nilint1** [comment]
for the chron, is there a specific language we want to go with to be consistent?  If not, I can work on it and it will be in python.  

I know how much @esilverm loves python.

The plan will be a one shot program that queries google and then send the results to the database.  The chron program (whatever AWS uses) will control when the python gets executed.

**Comment by esilverm** [comment]
I believe that the actual quota is moreso around 10,000 requests per day which is a bit better than 100, but this is a good proposal

**Comment by Nilint1** [comment]
See pull request #194

**Comment by esilverm** [comment]
Is this issue ready to be closed

**Comment by Nilint1** [comment]
it can be closed as soon as the chron job is deployed.

**Comment by Nilint1** [comment]
complete
